---
title: "BERT - Cluster and MDS"
author: "Aleksandr Zhuravlev"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(lsa)
library(cluster)
library(tidyverse)
library(ggpubr)
```

```{r data, message=FALSE, warning=FALSE}
# load questions and corresponding pooled embeddings
questions <- read_csv("data/questions.csv")
# embeddings <- read_csv("data/embeddings_python.csv")
embeddings <- read_csv("data/Embeddings_CLS.csv")[2:769]

topics<- read_csv("data/topic_probs.csv")

colnames(topics) <- c("url", paste0("Topic_", c(1:20)))

```

```{r smart merge}

problem_doc <- anti_join(questions, topics, by="url") %>% pull(1)

problem_number <- which(questions$url==problem_doc)

questions<- questions[-problem_number, ]
embeddings<- embeddings[-problem_number, ]
```

```{r pre-process topics}

topic_names<- c("url", "Trade", "Gender and discrimination",
                                "Fishery",
                                "Biodiversity",
                                "Transport",
                                "Democratic institutions",
                                "Finance",
                                "COVID",
                                "Military",
                                "Refugees",
                                "Pollution",
                                "Sustainable production",
                                "Education and youth",
                                "Energy",
                                "Nonsense",
                                "Nonsense 2",
                                "Poland stuff",
                                "Healthcare",
                                "Internet",
                                "Terrorism")
colnames(topics)<-topic_names 


max_topics<- topics %>%
  pivot_longer(-url, names_to = "Topic", values_to = "Prob") %>%
  group_by(url) %>%
  arrange(desc(Prob)) %>%
  slice_max(Prob, n = 1, with_ties = FALSE)
  
  
```

```{r train PCA, eval=FALSE}

embed_mat <- as.matrix(embeddings)

PCA_res <- prcomp(embed_mat, center=TRUE, scale=TRUE)

```

```{r visualise PCA, eval=FALSE}
as.data.frame(PCA_res$x) %>%
  cbind(max_topics) %>%
  mutate(Topic = as.factor(Topic)) %>%
  ggplot(., aes(x=PC1, y=PC2, colour=Topic)) + geom_point() + theme_bw() 
```


```{r MDS, eval=FALSE}
cor_topics <-topics %>%
  select(-url) %>%
  cor()

cosine_siimilarities<- cosine(cor_topics)
ttt <- outer(diag(cosine_siimilarities), diag(cosine_siimilarities)) / (cosine_siimilarities * t(cosine_siimilarities))
ttt[is.infinite(ttt)] <- NA
dis <- as.dist(log(ttt)) 
dis[is.na(dis)] <- 1                       # Replace NA by 1
res <- mds(dis)                            # Do ratio MDS with ndim = 2
op <- par(mfrow = c(1, 2))                 # Two plots next to each other

plot(res, las = 1, col = "red")            # Make a configuration plot
plot(res, plot.type = "Shepard", las = 1,  # Make a Shepard plot
     sub = paste("Stress-1 =",formatC(res$stress, digits = 6)))
par(op) 
```


```{r clusters, eval=FALSE}
library(fastcluster)
dist_embed<-dist(embeddings)
clusters <- fastcluster::hclust(dist_embed, method = "complete")
```

```{r visualise clusters, eval=FALSE}
cluster_labels<- cutree(clusters, k=8)

as.data.frame(PCA_res$x) %>%
  mutate(Cluster = as.factor(cluster_labels)) %>%
  ggplot(., aes(x=PC1, y=PC2, colour=Cluster)) + geom_point() + theme_bw() 
```

```{r cor_plot, eval=FALSE}

topics_clean<- topics %>% dplyr::select(-url)
# Calculate correlations between topics and embeddings
correlation_matrix <- cor(topics_clean, embeddings)

# Convert correlation matrix to dataframe
correlation_df <- as.data.frame(correlation_matrix)

# Optionally, you can add row and column names to the dataframe
row_names <- topic_names[2:21]
col_names <- paste0("embed_", colnames(embeddings))
rownames(correlation_df) <- row_names
colnames(correlation_df) <- col_names

# View the resulting dataframe
head(correlation_df)

correlation_df %>%
  mutate(Topic = rownames(correlation_df)) %>%
  pivot_longer(-Topic, names_to="Embedding", values_to="Correlation") %>%
  ggplot(., aes(x=Embedding, y=Topic, fill=Correlation)) + geom_tile() +
  scale_fill_gradient(low = "lightgray", high = "darkblue", na.value = "grey50") +
  labs(title = "Correlations of topics and embeddings",
       x = "Embedding",
       y = "Topic",
       fill = "Correlation") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(axis.text.x = element_text(size = 1))
```
```{r plot cosine similarities, eval=FALSE}
cosine_sims<- as.data.frame(cosine(as.matrix(embeddings))) 

cosine_sims %>%
  mutate(Topic_1 = colnames(embeddings)) %>%
  pivot_longer(-Topic_1, names_to="Topic_2", values_to="Cosine similarity") %>%
  ggplot(., aes(x=Topic_2, y=Topic_1, fill=`Cosine similarity`)) + geom_tile() +
  scale_fill_gradient(low = "lightgray", high = "darkblue", na.value = "grey50") +
  labs(title = "Correlations of topics and embeddings",
       x = "Topic 2",
       y = "Topic 1",
       fill = "Cosine similarity") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(axis.text.x = element_text(size = 8))
  
```
```{r Summed Embeddings - Groups}
mean_group_embeds<- embeddings %>%
  mutate(Group = data$party) %>%
  group_by(Group) %>%
  summarise(across(where(is.numeric), mean, na.rm = TRUE)) %>%
  pivot_longer(cols = -Group, names_to = "Embed", values_to = "Value") %>%
  pivot_wider(names_from = Group, values_from = Value) %>%
  dplyr::select(-Embed)

```

```{r cosine_similarities - Groups}
embed_cosine_sim<-cosine(as.matrix(mean_group_embeds))

group_sims<- as.data.frame(embed_cosine_sim) %>%
  mutate(Group_1 = rownames(embed_cosine_sim)) %>%
  pivot_longer(-Group_1, names_to="Group_2", values_to="Cosine similarity") %>%
  ggplot(., aes(x=Group_2, y=Group_1, fill=`Cosine similarity`)) + geom_tile() +
  scale_fill_gradient(low = "lightgray", high = "cornflowerblue", na.value = "grey50") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title="(a) Group level", x="", y="") + coord_fixed(ratio = 1)

group_sims
```

```{r Summed Embeddings - Region}
mean_region_embeds<- embeddings %>%
  mutate(Region = data$region) %>%
  group_by(Region) %>%
  summarise(across(where(is.numeric), mean, na.rm = TRUE)) %>%
  pivot_longer(cols = -Region, names_to = "Embed", values_to = "Value") %>%
  pivot_wider(names_from = Region, values_from = Value) %>%
  dplyr::select(-Embed)

```

```{r cosine_similarities - Region}
embed_cosine_sim_region<-cosine(as.matrix(mean_region_embeds))

region_sims<- as.data.frame(embed_cosine_sim_region) %>%
  mutate(Region_1 = rownames(embed_cosine_sim_region)) %>%
  pivot_longer(-Region_1, names_to="Region_2", values_to="Cosine similarity") %>%
  ggplot(., aes(x=Region_2, y=Region_1, fill=`Cosine similarity`)) + geom_tile() +
  scale_fill_gradient(low = "lightgray", high = "cornflowerblue", na.value = "grey50") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title="(b) Region level", x="", y="") + coord_fixed(ratio = 1)

region_sims
```


```{r similarities combined}
ggarrange(group_sims, region_sims, ncol=2) # Save with 1200 x 500
```